simpleblog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware'=>['checkadmin']], function(){
	Route::get('/admin', 'AdminController@index');
	Route::get('/create', 'AdminController@create');
});





Route::get('/single', function(){
	return view('single');
})->name('sin');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/posts', 'PostController');
Route::resource('/postcategory', 'PostCategoryController');

Route::get('/addcategories', 'AddCategoryController@index')->name('addcategories');
Route::post('/addcategories/store', 'AddCategoryController@store')->name('addcategories.store');

simpleblog/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
   protected $fillable = ['title', 'description', 'image', 'post_category_id', 'user_id'];

   public function user()
   {
   	return $this->belongsTo('App\User');
   }

   public function post_category()
   {
   	return $this->belongsTo('App\PostCategory');
   }
}

simpleblog/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Post;
use App\PostCategory;
use Illuminate\Support\Facades\Session;
use App\Mail\PostCreated;

class PostController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();
        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $postcategorys = PostCategory::all();
        return view('posts.create', compact('postcategorys'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|unique:posts',
            'description'=> 'required',
            'image' => 'required'
        ]);
        $input = $request->all();
        //dd($input);
        if(isset($input['image'])){
            $input['image'] = $this->upload($input['image']);
        }else{
            $input['image'] = 'img/default.jpg';
        }
        $input['user_id'] = Auth::user()->id;
        Post::create($input);

        \Mail::to($request->user())->send(new PostCreated($request->user()->name));

        Session::flash('status', 'Post Created Successfully');
        return redirect('posts');
    }

     public function upload($file)
    {
        $extension = $file->getClientOriginalExtension();
        $sha = sha1($file->getClientOriginalName());
        $filename = date('Y-m-d-h-i-s')."-".$sha.".".$extension;
        $path = public_path('img/posts/');
        $file->move($path, $filename);
        return 'img/posts/'.$filename;
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::findOrFail($id);
        return view('posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        $postcategorys = PostCategory::all();
        //dd($post);
        return view('posts.edit')->with('post', $post)->with('postcategorys', $postcategorys);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required|unique:posts',
            'description'=> 'required',
        ]);
        $post = Post::findOrFail($id);
        $input = $request->all();
        if(isset($input['image'])){
            $input['image'] = $this->upload($input['image']);
        }
        $input['user_id'] = Auth::user()->id;
        $post->update($input);
        Session::flash('status', 'Post Updated Successfully');
        return redirect('posts');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Post::findOrFail($id)->delete();
        return redirect()->back();
    }
}

simpleblog/resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h1>Create posts <a href="{{route('posts.index')}}" class="btn btn-primary pull-right">Back</a></h1>
				@if(count($errors->all())>0)
				<div class="alert alert-danger">
					<ul>
						
					@foreach($errors->all() as $error)
						<li>{{$error}}</li>
					@endforeach
					</ul>
				</div>
				@endif
				<form action="{{route('posts.store')}}" method="POST" enctype="multipart/form-data">
					{{csrf_field()}}
					<div class="form-group">
						<label for="title">Title</label>
						<input type="text" name="title" id="title" class="form-control"> 
					</div>
					<div class="form-group">
						<label for="image">Select a thumbnail</label>
						<input type="file" name="image" id="image">
					</div>
					<div class="form-group">
						<label for="post_category_id">Select a Category</label>
						<select name="post_category_id" id="post_category_id">
							@foreach($postcategorys as $postcategory)
							<option value="{{$postcategory->id}}">{{$postcategory->name}}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group">
						<label for="description">Description</label>
						<textarea name="description" id="description" cols="30" rows="10" class="form-control"></textarea>
					</div>
					<button class="btn btn-success">Create</button>
				</form>
				
			</div>
		</div>
	</div>
@endsection

simpleblog/resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h1>Edit posts <a href="{{route('posts.index')}}" class="btn btn-primary pull-right">Back</a></h1>
				@if(count($errors->all())>0)
				<div class="alert alert-danger">
					<ul>
						
					@foreach($errors->all() as $error)
						<li>{{$error}}</li>
					@endforeach
					</ul>
				</div>
				@endif
				<form action="{{route('posts.update', $post->id)}}" method="POST" enctype="multipart/form-data">
					{{method_field('PUT')}}
					{{csrf_field()}}
					<div class="form-group">
						<label for="title">Title</label>
						<input type="text" value="{{$post->title}}" name="title" id="title" class="form-control" >
					</div>
					<div class="row">
						<div class="col-sm-6">
							<div class="form-group">
								<label for="image">Select a thumbnail</label>
								<input type="file" name="image" id="image" >
							</div>
							<div class="form-group">
								<label for="post_category_id">Select a Category</label>
								<select name="post_category_id" id="post_category_id">
									@foreach($postcategorys as $postcategory)
									<option value="{{$postcategory->id}}" @if($postcategory->id == $post->post_category_id ) Selected @endif>{{$postcategory->name}}</option>
									@endforeach
								</select>
							</div>
						</div>
						<div class="col-sm-6">
							<img src="{{asset($post->image)}}" alt="" class="img-responsive" >
						</div>
					</div>
					
					<div class="form-group">
						<label for="description">Description</label>
						<textarea name="description" id="description" cols="30" rows="10" class="form-control">{{$post->description}}</textarea>
					</div>
					<button class="btn btn-success">Update</button>
				</form>
			</div>
		</div>
	</div>
@endsection

simpleblog/resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h1>All posts <a href="{{route('posts.create')}}" class="btn btn-primary pull-right">Create Post</a></h1>
				@if (session('status'))
				    <div class="alert alert-success">
				        {{ session('status') }}
				    </div>
				@endif
				<table class="display table table-bordered" id="myTable" cellspacing="0" width="100%">
					<thead>
						<tr>
							<td>Sl</td>
							<td>Title</td>
							<!-- <td>Description</td> -->
							<td>Created By</td>
							<td>Category</td>
							<td>Image</td>
							<td>Date</td>
							<td width="150"></td>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<td>Sl</td>
							<td>Title</td>
							<!-- <td>Description</td> -->
							<td>Created By</td>
							<td>Category</td>
							<td>Image</td>
							<td>Date</td>
							<td width="150"></td>
						</tr>
					</tfoot>
					<tbody>
						@foreach($posts as $post)
						<tr>
							<td>{{$post->id}}</td>
							<td>{{$post->title}}</td>
							<!-- <td class="post-desc">{{$post->description}}</td> -->
							<td>{{$post->user->name}}</td>
							<td>{{$post->post_category->name}}</td>
							<td><img src="{{$post->image}}" alt="" class="img-responsive"></td>
							<td>{{$post->created_at->toFormattedDateString()}}</td>
							<td>
								<a class="btn btn-primary btn-sm" href="{{route('posts.show', $post->id)}}">View</a>
								<a class="btn btn-warning btn-sm" href="{{route('posts.edit', $post->id)}}">Edit</a>
								<a href="#" onclick="return confirm('are you sure?')">
									<form action="{{route('posts.destroy', $post->id)}}" method="POST">
										{{csrf_field()}}
										{{method_field('DELETE')}}
										<input type="submit" class="btn btn-danger btn-sm" value="Delete">
									</form>
								</a>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
				
			</div>
		</div>
	</div>
@endsection
@section('scripts')
	<script type="text/javascript">
		$(document).ready(function(){
		    $('#myTable').DataTable();
		});
	</script>
@endsection

simpleblog/resources/views/posts/postcategory.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h1>All Categories <a href="#" class="btn btn-primary pull-right" data-toggle="modal" data-target="#myModal">Add a category</a></h1>

				<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
				  <div class="modal-dialog" role="document">
				    <div class="modal-content">
				      <div class="modal-header">
				        <h4 class="modal-title" id="myModalLabel">Create Category</h4>
				      </div>
				      <div class="modal-body">
				        <form action="{{route('postcategory.store')}}" method="POST">
				        	{{csrf_field()}}
				        	<div class="form-group">
				        		<label for="name">Post Category Name</label>
				        		<input type="text" name="name"  id="name" class="form-control">
				        	</div>
				        	<div class="form-group">
				        		<label for="slug">Post Category Slug</label>
				        		<input type="text" name="slug"  id="slug" class="form-control">
				        	</div>
				        	<div class="form-group">
				        		<label for="description">Post Category Description</label>
				        		<textarea name="description" id="description" cols="30" rows="5" class="form-control"></textarea>
				        	</div>
				        	<button type="submit" class="btn btn-primary">Add</button>
				        </form>
				      </div>
				      <div class="modal-footer">
				        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				      </div>
				    </div>
				  </div>
				</div>
				
				<div class="post-categories">
					<div class="btn-group" role="group" aria-label="...">

						@foreach($postcategorys as $postcategory)
					  <a href="{{route('postcategory.show', $postcategory->id)}}"><button type="button" class="btn btn-default">{{$postcategory->name}}</button></a>
					  
					  @endforeach
					</div>
				</div>
				
				<table class="table table-bordered table-striped">
					<thead>
						<tr>
							<td>Sl</td>
							<td>Title</td>
							<td>Description</td>
							<td>Created By</td>
							<td>Date</td>
						</tr>
					</thead>
					<tbody>
						@if(isset($posts))
						@foreach($posts as $post)
							<tr>
								<td>{{$post->id}}</td>
								<td>{{$post->title}}</td>
								<td>{{$post->description}}</td>
								<td><img src="{{asset($post->image)}}" alt="" class="img-responsive" width="100" height="100"></td>
								<td>{{$post->user->name}}</td>
								<td>{{$post->created_at->toFormattedDateString()}}</td>
							</tr>
						@endforeach
						
						@endif
					</tbody>
				</table>
				
			</div>
		</div>
	</div>
@endsection

simpleblog/resources/views/posts/show.blade.php
{{$post->name}}
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h1>Post Details : <a href="{{route('posts.index')}}" class="btn btn-primary pull-right">Back</a></h1>
				<h3>Post Title : {{$post->title}}</h3>
				<p>Description: {{$post->description}} </p>
			</div>
		</div>
	</div>
@endsection